#!/bin/bash

echo "🚀 Supabase Edge Function 배포 스크립트"
echo "======================================"
echo ""
echo "📋 배포 정보:"
echo "- 함수 이름: teamitaka-api"
echo "- Supabase 프로젝트: ${SUPABASE_PROJECT_ID:-your-project-id}"
echo "- 배포 URL: ${SUPABASE_URL}/functions/v1/teamitaka-api"
echo ""
echo "📝 배포 단계:"
echo "1. https://supabase.com/dashboard 접속"
echo "2. teamitaka 프로젝트 선택"
echo "3. Edge Functions → New Function"
echo "4. 함수 이름: teamitaka-api"
echo "5. 아래 코드를 복사하여 붙여넣기:"
echo ""
echo "=========================================="
cat supabase/functions/teamitaka-api/index.ts
echo ""
echo "=========================================="
echo ""
echo "6. Deploy 버튼 클릭"
echo ""
echo "✅ 배포 완료 후 테스트:"
echo "curl -X GET '${SUPABASE_URL}/functions/v1/teamitaka-api/api/health'"
echo ""
echo "📧 이메일 인증 테스트:"
echo "curl -X POST '${SUPABASE_URL}/functions/v1/teamitaka-api/api/auth/send-verification' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -H 'Origin: https://www.teamitaka.com' \\"
echo "  -d '{\"email\":\"test@example.com\"}'"
