version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: teamitaka-dev

    env_file:
      - .env  # DB_HOST=localhost, DB_USER=root, etc.

    ports:
      - "3000:3000"
    volumes:
      - ./:/app  # 로컬 소스 코드 변경 시 실시간 반영
    command: >
      bash -c "npx sequelize-cli db:migrate --url=$${DATABASE_URL} &&
               npx nodemon src/index.js"
