version: '3'
services:
  app:
    build: .
    environment:
      - DATABASE_URL=mysql://iam_user:Strong_Password123%2D@35.223.147.232:3306/teamitaka_database
    networks:
      - gcp-network
networks:
  gcp-network:
    external: true