paths:
  /api/projects:
    get:
      summary: 모든 프로젝트 조회
      responses:
        '200':
          description: 프로젝트 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string