openapi: 3.0.0
info:
  title: Teamitaka Backend API
  version: 1.0.0
  description: 팀이타카 백엔드 API 문서
servers:
  - url: http://localhost:3000
paths:
  /api/users:
    get:
      summary: 모든 사용자 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /api/projects:
    get:
      summary: 모든 프로젝트 조회
      responses:
        '200':
          description: 프로젝트 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string